# -*- coding: utf-8 -*-
"""
Merge K-sharded five-algorithm benchmark results generated by
run_five_algorithm_comparison_resume_optimized.py.

Core rules
----------
1. Final PF quality metrics are always recomputed from the merged Pareto fronts
   with the optimized runner. Existing per-shard HV/IGD+/epsilon values are not
   trusted as final merged results.
2. HV-FE and IGD+-FE curves are rebuilt from raw snapshot points, using the
   existing hv_fe_curve.csv files only as checkpoint metadata. This guarantees
   one common implementation and preserves empty early checkpoints.
3. When duplicate run keys exist, the selected run, Pareto front, convergence
   history, checkpoint metadata, and snapshot points must all come from the
   same selected shard.
4. Every fixed (K, rho) block must contain all configured algorithms and seeds.

Edit RUNNER_FILE, SHARD_DIRS, and MERGED_OUTPUT_DIR before running.
"""
from __future__ import annotations

import importlib.util
import json
import shutil
import sys
from pathlib import Path
from typing import Any, Iterable, Sequence

import numpy as np
import pandas as pd


# =============================================================================
# 1. Configuration
# =============================================================================
if "__file__" in globals():
    SCRIPT_DIR = Path(__file__).resolve().parent
else:
    SCRIPT_DIR = Path.cwd().resolve()

RUNNER_FILE = SCRIPT_DIR / "run_five_algorithm_comparison_resume_optimized.py"

SHARD_DIRS: tuple[Path, ...] = (
    SCRIPT_DIR / "comparison_five_algorithms_formal_K10_V4",
    SCRIPT_DIR / "comparison_five_algorithms_formal_K15_V4",
    SCRIPT_DIR / "comparison_five_algorithms_formal_K20_V4",
)

MERGED_OUTPUT_DIR = SCRIPT_DIR / "comparison_five_algorithms_V4"
MERGED_FRONT_DIR = MERGED_OUTPUT_DIR / "fronts"
MERGED_HV_FE_DIR = MERGED_OUTPUT_DIR / "hv_fe_curves"
MERGED_EXCEL = MERGED_OUTPUT_DIR / "Comprehensive_results.xlsx"

COPY_FRONTS_TO_MERGED_DIR = False
STRICT_COMPLETENESS = True
REQUIRE_MANIFESTS = True
RECOMPUTE_HV_FE_FROM_SNAPSHOTS = True
ENFORCE_EXACT_HV_FE_MONOTONICITY = True
HV_MONOTONICITY_TOL = 1e-10
METRIC_EPS = 1e-12

RUN_KEY_COLUMNS = [
    "max_active_actions",
    "coverage_threshold",
    "algorithm",
    "seed",
]
CHECKPOINT_KEY_COLUMNS = RUN_KEY_COLUMNS + ["checkpoint_fraction"]
SNAPSHOT_OBJECTIVE_COLUMNS = [
    "min_objective_reputation",
    "min_objective_choice",
    "effective_cost",
]


# =============================================================================
# 2. Generic helpers
# =============================================================================
def load_module(path: Path, module_name: str) -> Any:
    if not path.exists():
        raise FileNotFoundError(f"Runner file not found: {path}")
    spec = importlib.util.spec_from_file_location(module_name, path)
    if spec is None or spec.loader is None:
        raise ImportError(f"Cannot import runner from {path}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[module_name] = module
    spec.loader.exec_module(module)
    return module


def read_required_csv(directory: Path, filename: str) -> pd.DataFrame:
    path = directory / filename
    if not path.exists():
        raise FileNotFoundError(f"Required file not found: {path}")
    return pd.read_csv(path)


def read_optional_csv(directory: Path, filename: str) -> pd.DataFrame:
    path = directory / filename
    return pd.read_csv(path) if path.exists() else pd.DataFrame()


def concatenate_nonempty(frames: Iterable[pd.DataFrame]) -> pd.DataFrame:
    valid = [frame for frame in frames if frame is not None and not frame.empty]
    return pd.concat(valid, ignore_index=True, sort=False) if valid else pd.DataFrame()


def canonical_rho(value: Any) -> float:
    return round(float(value), 10)


def canonicalize_run_keys(frame: pd.DataFrame) -> pd.DataFrame:
    result = frame.copy()
    missing = [column for column in RUN_KEY_COLUMNS if column not in result.columns]
    if missing:
        raise RuntimeError(f"Missing run-key columns: {missing}")

    result["max_active_actions"] = pd.to_numeric(
        result["max_active_actions"], errors="raise"
    ).astype(int)
    result["coverage_threshold"] = (
        pd.to_numeric(result["coverage_threshold"], errors="raise")
        .astype(float)
        .round(10)
    )
    result["algorithm"] = result["algorithm"].astype(str)
    result["seed"] = pd.to_numeric(result["seed"], errors="raise").astype(int)
    return result


def canonicalize_checkpoint_keys(frame: pd.DataFrame) -> pd.DataFrame:
    result = canonicalize_run_keys(frame)
    if "checkpoint_fraction" not in result.columns:
        raise RuntimeError("Missing checkpoint_fraction column.")
    result["checkpoint_fraction"] = (
        pd.to_numeric(result["checkpoint_fraction"], errors="raise")
        .astype(float)
        .round(10)
    )
    return result


def run_key_from_values(k: Any, rho: Any, algorithm: Any, seed: Any) -> tuple[int, float, str, int]:
    return int(k), canonical_rho(rho), str(algorithm), int(seed)


def add_source_metadata(frame: pd.DataFrame, directory: Path) -> pd.DataFrame:
    result = frame.copy()
    result["__source_shard"] = str(directory.resolve())
    result["__source_row"] = np.arange(len(result), dtype=int)
    return result


def _remove_stale_file(path: Path) -> None:
    if path.exists() and path.is_file():
        path.unlink()


def deduplicate_records(
    frame: pd.DataFrame,
    key_columns: Sequence[str],
    dataset_name: str,
    audit_path: Path,
) -> pd.DataFrame:
    """Keep the last input record for each key and write a complete audit."""
    if frame.empty:
        _remove_stale_file(audit_path)
        return frame.copy()

    missing = [column for column in key_columns if column not in frame.columns]
    if missing:
        raise RuntimeError(
            f"Cannot deduplicate {dataset_name}; missing key columns: {missing}"
        )

    duplicate_mask = frame.duplicated(list(key_columns), keep=False)
    if not duplicate_mask.any():
        _remove_stale_file(audit_path)
        return frame.copy().reset_index(drop=True)

    keep_mask = ~frame.duplicated(list(key_columns), keep="last")
    audit = frame.loc[duplicate_mask].copy()
    audit["duplicate_resolution"] = np.where(
        keep_mask.loc[audit.index], "kept_last", "discarded"
    )
    sort_columns = list(key_columns) + [
        column
        for column in ("__source_shard", "__source_row")
        if column in audit.columns
    ]
    audit = audit.sort_values(sort_columns, kind="mergesort")
    audit_path.parent.mkdir(parents=True, exist_ok=True)
    audit.to_csv(audit_path, index=False, encoding="utf-8-sig")

    duplicate_key_count = int(
        frame.loc[duplicate_mask, list(key_columns)].drop_duplicates().shape[0]
    )
    discarded_count = int((duplicate_mask & ~keep_mask).sum())
    print(
        f"WARNING: {dataset_name} contains {duplicate_key_count} duplicate keys; "
        f"discarded {discarded_count} earlier records and kept the last record."
    )
    print(f"Duplicate audit: {audit_path}")
    return frame.loc[keep_mask].copy().reset_index(drop=True)


def selected_source_map(metrics_with_source: pd.DataFrame) -> dict[tuple[int, float, str, int], str]:
    mapping: dict[tuple[int, float, str, int], str] = {}
    columns = RUN_KEY_COLUMNS + ["__source_shard"]
    for k, rho, algorithm, seed, source in metrics_with_source[columns].itertuples(
        index=False, name=None
    ):
        key = run_key_from_values(k, rho, algorithm, seed)
        mapping[key] = str(source)
    return mapping


def filter_to_selected_sources(
    frame: pd.DataFrame,
    source_by_run: dict[tuple[int, float, str, int], str],
    dataset_name: str,
) -> pd.DataFrame:
    if frame.empty:
        return frame.copy()
    if "__source_shard" not in frame.columns:
        raise RuntimeError(f"{dataset_name} has no __source_shard column.")

    keys = [
        run_key_from_values(k, rho, algorithm, seed)
        for k, rho, algorithm, seed in frame[RUN_KEY_COLUMNS].itertuples(
            index=False, name=None
        )
    ]
    expected_sources = pd.Series(
        [source_by_run.get(key) for key in keys], index=frame.index, dtype="object"
    )
    known = expected_sources.notna()
    matching = frame["__source_shard"].astype(str).eq(expected_sources.astype(str))

    ignored_unknown = int((~known).sum())
    ignored_wrong_source = int((known & ~matching).sum())
    if ignored_unknown or ignored_wrong_source:
        print(
            f"INFO: {dataset_name}: ignored {ignored_unknown} rows without a selected "
            f"run and {ignored_wrong_source} rows from non-selected duplicate shards."
        )
    return frame.loc[known & matching].copy().reset_index(drop=True)


def normalized_json(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":"))


# =============================================================================
# 3. Manifest and completeness validation
# =============================================================================
def read_manifest(shard_dir: Path) -> dict[str, Any]:
    path = shard_dir / "_resume" / "manifest.json"
    if not path.exists():
        if REQUIRE_MANIFESTS:
            raise FileNotFoundError(f"Resume manifest not found: {path}")
        return {}
    with path.open("r", encoding="utf-8") as handle:
        return json.load(handle)


def validate_manifest_compatibility(
    shard_dirs: tuple[Path, ...],
) -> tuple[pd.DataFrame, dict[str, Any]]:
    manifests: list[dict[str, Any]] = []
    rows: list[dict[str, Any]] = []

    for directory in shard_dirs:
        manifest = read_manifest(directory)
        configuration = manifest.get("configuration", {})
        manifests.append(configuration)
        rows.append(
            {
                "shard": str(directory.resolve()),
                "schema_version": manifest.get("schema_version"),
                "signature": manifest.get("signature"),
                "runner_sha256": configuration.get("runner_sha256"),
                "core_sha256": configuration.get("core_sha256"),
                "moead_adapter_sha256": configuration.get("moead_adapter_sha256"),
                "shamode_adapter_sha256": configuration.get("shamode_adapter_sha256"),
                "seeds": normalized_json(configuration.get("seeds")),
                "generations": configuration.get("generations"),
                "n_options": configuration.get("n_options"),
                "max_active_action_scenarios": normalized_json(
                    configuration.get("max_active_action_scenarios")
                ),
                "coverage_threshold_scenarios": normalized_json(
                    configuration.get("coverage_threshold_scenarios")
                ),
                "algorithms": normalized_json(configuration.get("algorithms")),
                "population_multiplier": configuration.get("population_multiplier"),
                "minimum_population_size": configuration.get("minimum_population_size"),
                "maximum_population_size": configuration.get("maximum_population_size"),
                "fixed_generation_budget": configuration.get("fixed_generation_budget"),
                "metric_block_size": configuration.get("metric_block_size"),
                "moead_config": normalized_json(configuration.get("moead_config")),
                "hv_fe_checkpoint_fractions": normalized_json(
                    configuration.get("hv_fe_checkpoint_fractions")
                ),
            }
        )

    comparison = pd.DataFrame(rows)
    if comparison.empty:
        raise RuntimeError("No shard manifests were loaded.")

    critical_fields = [
        "schema_version",
        "core_sha256",
        "moead_adapter_sha256",
        "shamode_adapter_sha256",
        "seeds",
        "generations",
        "n_options",
        "coverage_threshold_scenarios",
        "algorithms",
        "population_multiplier",
        "minimum_population_size",
        "maximum_population_size",
        "fixed_generation_budget",
        "metric_block_size",
        "moead_config",
        "hv_fe_checkpoint_fractions",
    ]

    missing_fields = [
        field for field in critical_fields if comparison[field].isna().any()
    ]
    # JSON-encoded None appears as the literal string "null".
    missing_fields.extend(
        field
        for field in critical_fields
        if comparison[field].astype(str).eq("null").any() and field not in missing_fields
    )
    if missing_fields:
        raise RuntimeError(
            "Shard manifests are missing optimization-critical fields: "
            f"{missing_fields}\n{comparison[['shard'] + missing_fields].to_string(index=False)}"
        )

    inconsistent = [
        field for field in critical_fields if comparison[field].astype(str).nunique() > 1
    ]
    if inconsistent:
        raise RuntimeError(
            "Shard manifests differ on optimization-critical fields: "
            f"{inconsistent}\n"
            + comparison[["shard"] + inconsistent].to_string(index=False)
        )

    if comparison["runner_sha256"].dropna().astype(str).nunique() > 1:
        print(
            "WARNING: runner_sha256 differs across K shards. This is acceptable only "
            "when the differences are limited to shard-specific settings such as K and "
            "OUTPUT_DIR. Final PF and HV-FE metrics will be recomputed uniformly with "
            f"{RUNNER_FILE.name}."
        )

    return comparison, manifests[0]


def validate_shard_k_configuration(
    shard_dir: Path,
    frame: pd.DataFrame,
    manifest: dict[str, Any],
) -> None:
    configured = {
        int(value) for value in manifest.get("max_active_action_scenarios", [])
    }
    observed = set(frame["max_active_actions"].astype(int).unique())
    if configured and observed != configured:
        raise RuntimeError(
            f"Shard K mismatch for {shard_dir}: manifest={sorted(configured)}, "
            f"run_metrics={sorted(observed)}"
        )


def validate_runner_against_manifest(runner: Any, common: dict[str, Any]) -> None:
    manifest_algorithms = tuple(
        str(item["name"]) for item in common.get("algorithms", [])
    )
    runner_algorithms = tuple(str(value) for value in runner.ALGORITHM_NAMES)
    if manifest_algorithms != runner_algorithms:
        raise RuntimeError(
            "The merge runner algorithm order differs from the shard manifests.\n"
            f"Manifest: {manifest_algorithms}\nRunner:   {runner_algorithms}"
        )

    manifest_checkpoints = tuple(
        round(float(value), 10)
        for value in common.get("hv_fe_checkpoint_fractions", [])
    )
    runner_checkpoints = tuple(
        round(float(value), 10)
        for value in runner.HV_FE_CHECKPOINT_FRACTIONS
    )
    if manifest_checkpoints != runner_checkpoints:
        raise RuntimeError(
            "HV-FE checkpoint fractions differ between the runner and manifests.\n"
            f"Manifest: {manifest_checkpoints}\nRunner:   {runner_checkpoints}"
        )

    manifest_block_size = int(common.get("metric_block_size"))
    runner_block_size = int(getattr(runner, "METRIC_BLOCK_SIZE", -1))
    if manifest_block_size != runner_block_size:
        raise RuntimeError(
            "The optimized metric block size differs between the runner and manifests: "
            f"manifest={manifest_block_size}, runner={runner_block_size}."
        )


def validate_scenario_completeness(
    metrics_with_source: pd.DataFrame,
    expected_algorithms: Sequence[str],
    expected_seeds: Sequence[int],
    expected_rhos: Sequence[float],
) -> pd.DataFrame:
    expected_algorithms = tuple(str(value) for value in expected_algorithms)
    expected_seeds = tuple(int(value) for value in expected_seeds)
    expected_rhos = tuple(canonical_rho(value) for value in expected_rhos)

    observed_algorithms = set(metrics_with_source["algorithm"].astype(str).unique())
    unexpected_algorithms = observed_algorithms - set(expected_algorithms)
    if unexpected_algorithms:
        raise RuntimeError(f"Unexpected algorithms in run_metrics: {sorted(unexpected_algorithms)}")

    rows: list[dict[str, Any]] = []
    k_levels = sorted(metrics_with_source["max_active_actions"].astype(int).unique())
    expected_pairs = {
        (algorithm, seed)
        for algorithm in expected_algorithms
        for seed in expected_seeds
    }

    for k in k_levels:
        for rho in expected_rhos:
            group = metrics_with_source.loc[
                (metrics_with_source["max_active_actions"] == int(k))
                & np.isclose(
                    metrics_with_source["coverage_threshold"].astype(float),
                    float(rho),
                )
            ]
            run_pairs = set(
                zip(group["algorithm"].astype(str), group["seed"].astype(int))
            )
            missing = sorted(expected_pairs - run_pairs)
            extra = sorted(run_pairs - expected_pairs)
            failed = int((group["status"].astype(str) != "success").sum())
            source_count = int(group["__source_shard"].astype(str).nunique()) if len(group) else 0
            rows.append(
                {
                    "max_active_actions": int(k),
                    "coverage_threshold": float(rho),
                    "n_run_records": int(len(group)),
                    "expected_run_records": int(len(expected_pairs)),
                    "n_missing": int(len(missing)),
                    "n_extra": int(len(extra)),
                    "n_failed": failed,
                    "n_source_shards": source_count,
                    "missing_examples": " | ".join(
                        f"{algorithm}/seed={seed}" for algorithm, seed in missing[:10]
                    ),
                    "extra_examples": " | ".join(
                        f"{algorithm}/seed={seed}" for algorithm, seed in extra[:10]
                    ),
                }
            )

    report = pd.DataFrame(rows)
    bad = report.loc[
        (report["n_missing"] > 0)
        | (report["n_extra"] > 0)
        | (report["n_failed"] > 0)
        | (report["n_source_shards"] != 1)
    ]
    if STRICT_COMPLETENESS and not bad.empty:
        raise RuntimeError(
            "Incomplete, failed, or cross-shard scenario blocks were found:\n"
            + bad.to_string(index=False)
        )
    return report


# =============================================================================
# 4. Pareto fronts and source consistency
# =============================================================================
def load_all_fronts(
    shard_dirs: tuple[Path, ...],
) -> tuple[
    dict[tuple[int, float, str, int], pd.DataFrame],
    dict[tuple[int, float, str, int], str],
]:
    fronts: dict[tuple[int, float, str, int], pd.DataFrame] = {}
    front_sources: dict[tuple[int, float, str, int], str] = {}
    front_paths: dict[tuple[int, float, str, int], str] = {}
    duplicate_front_rows: list[dict[str, Any]] = []

    if COPY_FRONTS_TO_MERGED_DIR:
        MERGED_FRONT_DIR.mkdir(parents=True, exist_ok=True)

    for shard_dir in shard_dirs:
        front_dir = shard_dir / "fronts"
        if not front_dir.exists():
            raise FileNotFoundError(f"Front directory not found: {front_dir}")

        for path in sorted(front_dir.glob("*.csv")):
            frame = pd.read_csv(path)
            if frame.empty:
                raise RuntimeError(f"Empty Pareto-front file: {path}")
            frame = canonicalize_run_keys(frame)

            unique_keys = frame[RUN_KEY_COLUMNS].drop_duplicates()
            if len(unique_keys) != 1:
                raise RuntimeError(f"Front metadata are not constant within {path}")
            k, rho, algorithm, seed = unique_keys.iloc[0].tolist()
            key = run_key_from_values(k, rho, algorithm, seed)
            source = str(shard_dir.resolve())

            if key in fronts:
                duplicate_front_rows.extend(
                    [
                        {
                            **dict(zip(RUN_KEY_COLUMNS, key)),
                            "front_path": front_paths[key],
                            "duplicate_resolution": "discarded_earlier",
                        },
                        {
                            **dict(zip(RUN_KEY_COLUMNS, key)),
                            "front_path": str(path.resolve()),
                            "duplicate_resolution": "kept_last",
                        },
                    ]
                )

            fronts[key] = frame
            front_sources[key] = source
            front_paths[key] = str(path.resolve())

    if not fronts:
        raise RuntimeError("No Pareto fronts were loaded.")

    audit_path = MERGED_OUTPUT_DIR / "duplicate_fronts_audit.csv"
    if duplicate_front_rows:
        duplicate_fronts = pd.DataFrame(duplicate_front_rows).drop_duplicates()
        duplicate_fronts.to_csv(audit_path, index=False, encoding="utf-8-sig")
        print(
            "WARNING: duplicate Pareto-front run keys were found; the last shard "
            "in SHARD_DIRS was retained."
        )
        print(f"Duplicate audit: {audit_path}")
    else:
        _remove_stale_file(audit_path)

    return fronts, front_sources


def validate_front_source_consistency(
    successful_keys: set[tuple[int, float, str, int]],
    source_by_run: dict[tuple[int, float, str, int], str],
    fronts: dict[tuple[int, float, str, int], pd.DataFrame],
    front_sources: dict[tuple[int, float, str, int], str],
) -> None:
    missing_fronts = sorted(successful_keys - set(fronts))
    extra_fronts = sorted(set(fronts) - successful_keys)
    if missing_fronts or extra_fronts:
        raise RuntimeError(
            "Metrics/front mismatch.\n"
            f"Missing fronts: {missing_fronts[:10]}\n"
            f"Extra fronts: {extra_fronts[:10]}"
        )

    mismatches = [
        (key, source_by_run[key], front_sources[key])
        for key in sorted(successful_keys)
        if str(source_by_run[key]) != str(front_sources[key])
    ]
    if mismatches:
        raise RuntimeError(
            "Deduplicated metrics and Pareto fronts were selected from different "
            "shards. First mismatches:\n"
            + "\n".join(
                f"{key}: metrics={metric_source}; front={front_source}"
                for key, metric_source, front_source in mismatches[:10]
            )
        )


def infer_service_element_count(fronts: dict[Any, pd.DataFrame]) -> int:
    expected_columns: tuple[str, ...] | None = None
    for key, frame in fronts.items():
        decision_columns = tuple(
            sorted(
                str(column)
                for column in frame.columns
                if str(column).startswith("x_")
            )
        )
        if not decision_columns:
            raise RuntimeError(
                f"Cannot infer service-element count for front {key}; no x_ columns."
            )
        if expected_columns is None:
            expected_columns = decision_columns
        elif decision_columns != expected_columns:
            raise RuntimeError(
                f"Decision-variable columns differ across fronts. Front {key} is inconsistent."
            )
    assert expected_columns is not None
    return len(expected_columns)


# =============================================================================
# 5. HV-FE reconstruction and validation
# =============================================================================
def load_checkpoint_metadata(
    shard_dirs: tuple[Path, ...],
    source_by_run: dict[tuple[int, float, str, int], str],
) -> pd.DataFrame:
    frames: list[pd.DataFrame] = []
    for directory in shard_dirs:
        frame = canonicalize_checkpoint_keys(
            read_required_csv(directory, "hv_fe_curve.csv")
        )
        frames.append(add_source_metadata(frame, directory))

    metadata = concatenate_nonempty(frames)
    metadata = filter_to_selected_sources(
        metadata, source_by_run, "hv_fe_curve checkpoint metadata"
    )
    metadata = deduplicate_records(
        metadata,
        CHECKPOINT_KEY_COLUMNS,
        "hv_fe_curve checkpoint metadata",
        MERGED_OUTPUT_DIR / "duplicate_hv_fe_checkpoint_metadata_audit.csv",
    )
    return metadata


def load_snapshot_points(
    shard_dirs: tuple[Path, ...],
    source_by_run: dict[tuple[int, float, str, int], str],
) -> pd.DataFrame:
    frames: list[pd.DataFrame] = []
    for directory in shard_dirs:
        frame = read_required_csv(directory, "hv_fe_snapshot_points.csv.gz")
        if frame.empty:
            continue
        frame = canonicalize_checkpoint_keys(frame)
        missing = [
            column for column in SNAPSHOT_OBJECTIVE_COLUMNS if column not in frame.columns
        ]
        if missing:
            raise RuntimeError(
                f"Snapshot export in {directory} lacks objective columns: {missing}"
            )
        frames.append(add_source_metadata(frame, directory))

    points = concatenate_nonempty(frames)
    if points.empty:
        return points

    points = filter_to_selected_sources(points, source_by_run, "HV-FE snapshot points")
    for column in SNAPSHOT_OBJECTIVE_COLUMNS:
        points[column] = pd.to_numeric(points[column], errors="raise").astype(float)

    # snapshot_point_index is not used as a deduplication key because duplicated
    # exports can restart point numbering. Objective triples identify the points.
    point_keys = CHECKPOINT_KEY_COLUMNS + SNAPSHOT_OBJECTIVE_COLUMNS
    points = deduplicate_records(
        points,
        point_keys,
        "hv_fe_snapshot_points.csv.gz",
        MERGED_OUTPUT_DIR / "duplicate_hv_fe_snapshot_points_audit.csv",
    )
    return points


def validate_checkpoint_completeness(
    metadata: pd.DataFrame,
    successful_keys: set[tuple[int, float, str, int]],
    checkpoint_fractions: Sequence[float],
) -> pd.DataFrame:
    expected_fractions = tuple(round(float(value), 10) for value in checkpoint_fractions)
    rows: list[dict[str, Any]] = []

    grouped = {
        run_key_from_values(k, rho, algorithm, seed): group
        for (k, rho, algorithm, seed), group in metadata.groupby(
            RUN_KEY_COLUMNS, sort=False
        )
    }

    for key in sorted(successful_keys):
        group = grouped.get(key, pd.DataFrame())
        observed = (
            tuple(sorted(group["checkpoint_fraction"].astype(float).round(10).unique()))
            if not group.empty
            else tuple()
        )
        missing = sorted(set(expected_fractions) - set(observed))
        extra = sorted(set(observed) - set(expected_fractions))
        rows.append(
            {
                **dict(zip(RUN_KEY_COLUMNS, key)),
                "n_checkpoints": int(len(observed)),
                "expected_checkpoints": int(len(expected_fractions)),
                "n_missing": int(len(missing)),
                "n_extra": int(len(extra)),
                "missing_fractions": " | ".join(f"{value:.10g}" for value in missing),
                "extra_fractions": " | ".join(f"{value:.10g}" for value in extra),
            }
        )

    report = pd.DataFrame(rows)
    bad = report.loc[(report["n_missing"] > 0) | (report["n_extra"] > 0)]
    if STRICT_COMPLETENESS and not bad.empty:
        raise RuntimeError(
            "Incomplete HV-FE checkpoint metadata were found:\n"
            + bad.head(20).to_string(index=False)
        )
    return report


def validate_final_snapshot_points(
    points: pd.DataFrame,
    successful_keys: set[tuple[int, float, str, int]],
    final_checkpoint_fraction: float,
) -> None:
    if points.empty:
        raise RuntimeError(
            "No HV-FE snapshot points were loaded, although successful runs exist."
        )
    final_fraction = round(float(final_checkpoint_fraction), 10)
    final_points = points.loc[
        np.isclose(points["checkpoint_fraction"].astype(float), final_fraction)
    ]
    observed = {
        run_key_from_values(k, rho, algorithm, seed)
        for k, rho, algorithm, seed in final_points[RUN_KEY_COLUMNS].itertuples(
            index=False, name=None
        )
    }
    missing = sorted(successful_keys - observed)
    if missing:
        raise RuntimeError(
            "Successful runs without final-checkpoint snapshot points were found. "
            f"First missing keys: {missing[:10]}"
        )


def reconstruct_snapshot_records(
    metadata: pd.DataFrame,
    points: pd.DataFrame,
) -> list[dict[str, Any]]:
    point_groups: dict[tuple[int, float, str, int, float], np.ndarray] = {}
    if not points.empty:
        for keys, group in points.groupby(CHECKPOINT_KEY_COLUMNS, sort=False):
            k, rho, algorithm, seed, fraction = keys
            checkpoint_key = (
                int(k),
                canonical_rho(rho),
                str(algorithm),
                int(seed),
                round(float(fraction), 10),
            )
            values = group[SNAPSHOT_OBJECTIVE_COLUMNS].to_numpy(dtype=float)
            values = values[np.all(np.isfinite(values), axis=1)]
            if len(values):
                values = np.unique(np.round(values, 12), axis=0)
            point_groups[checkpoint_key] = values

    required_metadata = [
        "target_function_evaluations",
        "function_evaluations",
        "function_evaluation_budget",
    ]
    missing = [column for column in required_metadata if column not in metadata.columns]
    if missing:
        raise RuntimeError(f"HV-FE checkpoint metadata lack columns: {missing}")

    records: list[dict[str, Any]] = []
    for row in metadata.itertuples(index=False):
        checkpoint_key = (
            int(row.max_active_actions),
            canonical_rho(row.coverage_threshold),
            str(row.algorithm),
            int(row.seed),
            round(float(row.checkpoint_fraction), 10),
        )
        records.append(
            {
                "max_active_actions": checkpoint_key[0],
                "coverage_threshold": checkpoint_key[1],
                "scenario": getattr(row, "scenario", ""),
                "algorithm": checkpoint_key[2],
                "seed": checkpoint_key[3],
                "checkpoint_fraction": checkpoint_key[4],
                "target_function_evaluations": int(row.target_function_evaluations),
                "function_evaluations": int(row.function_evaluations),
                "function_evaluation_budget": int(row.function_evaluation_budget),
                "points": point_groups.get(
                    checkpoint_key, np.empty((0, 3), dtype=float)
                ).copy(),
            }
        )
    return records


def enforce_and_check_hv_fe_monotonicity(
    curve: pd.DataFrame,
) -> tuple[pd.DataFrame, pd.DataFrame]:
    if curve.empty:
        return curve.copy(), pd.DataFrame()

    result = curve.copy()
    result["hypervolume"] = pd.to_numeric(result["hypervolume"], errors="raise")
    result["igd_plus"] = pd.to_numeric(result["igd_plus"], errors="coerce")

    report_rows: list[dict[str, Any]] = []
    corrected_groups: list[pd.DataFrame] = []

    for keys, group in result.groupby(RUN_KEY_COLUMNS, sort=False):
        ordered = group.sort_values(
            ["actual_fe_fraction", "checkpoint_fraction"], kind="mergesort"
        ).copy()
        raw_hv = ordered["hypervolume"].to_numpy(dtype=float)
        raw_hv_diff = np.diff(raw_hv) if len(raw_hv) > 1 else np.empty(0)
        substantial_hv_drops = int(np.sum(raw_hv_diff < -HV_MONOTONICITY_TOL))
        tiny_hv_drops = int(
            np.sum((raw_hv_diff < 0.0) & (raw_hv_diff >= -HV_MONOTONICITY_TOL))
        )

        if substantial_hv_drops:
            raise RuntimeError(
                "Substantial non-monotone cumulative HV was found after rebuilding "
                f"the curve for run {keys}. Minimum difference={raw_hv_diff.min():.12g}."
            )

        corrected_hv = np.maximum.accumulate(raw_hv)
        n_hv_corrected = int(np.sum(corrected_hv > raw_hv + 0.0))
        if ENFORCE_EXACT_HV_FE_MONOTONICITY:
            ordered["hypervolume"] = corrected_hv

        igd = ordered["igd_plus"].to_numpy(dtype=float)
        finite_positions = np.flatnonzero(np.isfinite(igd))
        if len(finite_positions) > 1:
            finite_igd = igd[finite_positions]
            igd_diff = np.diff(finite_igd)
            substantial_igd_increases = int(np.sum(igd_diff > HV_MONOTONICITY_TOL))
            minimum_igd_diff = float(np.min(igd_diff)) if len(igd_diff) else np.nan
            maximum_igd_diff = float(np.max(igd_diff)) if len(igd_diff) else np.nan
        else:
            substantial_igd_increases = 0
            minimum_igd_diff = np.nan
            maximum_igd_diff = np.nan

        if substantial_igd_increases:
            raise RuntimeError(
                "Cumulative IGD+ increased materially after rebuilding the curve "
                f"for run {keys}; maximum increase={maximum_igd_diff:.12g}."
            )

        k, rho, algorithm, seed = keys
        report_rows.append(
            {
                "max_active_actions": int(k),
                "coverage_threshold": float(rho),
                "algorithm": str(algorithm),
                "seed": int(seed),
                "n_checkpoints": int(len(ordered)),
                "n_substantial_hv_drops": substantial_hv_drops,
                "n_tiny_hv_drops": tiny_hv_drops,
                "n_hv_values_clamped": n_hv_corrected,
                "minimum_raw_hv_difference": (
                    float(np.min(raw_hv_diff)) if len(raw_hv_diff) else np.nan
                ),
                "n_substantial_igd_increases": substantial_igd_increases,
                "minimum_igd_difference": minimum_igd_diff,
                "maximum_igd_difference": maximum_igd_diff,
            }
        )
        corrected_groups.append(ordered)

    corrected = pd.concat(corrected_groups, ignore_index=True, sort=False)
    corrected = corrected.sort_values(
        RUN_KEY_COLUMNS + ["actual_fe_fraction", "checkpoint_fraction"],
        kind="mergesort",
    ).reset_index(drop=True)
    return corrected, pd.DataFrame(report_rows)


# =============================================================================
# 6. Other merged datasets
# =============================================================================
def load_convergence_history(
    shard_dirs: tuple[Path, ...],
    source_by_run: dict[tuple[int, float, str, int], str],
) -> pd.DataFrame:
    frames: list[pd.DataFrame] = []
    for directory in shard_dirs:
        frame = read_optional_csv(directory, "convergence_history.csv")
        if frame.empty:
            continue
        frame = canonicalize_run_keys(frame)
        frames.append(add_source_metadata(frame, directory))

    convergence = concatenate_nonempty(frames)
    if convergence.empty:
        return convergence
    convergence = filter_to_selected_sources(
        convergence, source_by_run, "convergence_history.csv"
    )

    if "function_evaluations" in convergence.columns:
        convergence["function_evaluations"] = pd.to_numeric(
            convergence["function_evaluations"], errors="raise"
        ).astype(int)
        keys = RUN_KEY_COLUMNS + ["function_evaluations"]
    elif "generation" in convergence.columns:
        convergence["generation"] = pd.to_numeric(
            convergence["generation"], errors="raise"
        ).astype(int)
        keys = RUN_KEY_COLUMNS + ["generation"]
    else:
        raise RuntimeError(
            "convergence_history.csv has neither function_evaluations nor generation."
        )

    convergence = deduplicate_records(
        convergence,
        keys,
        "convergence_history.csv",
        MERGED_OUTPUT_DIR / "duplicate_convergence_history_audit.csv",
    )
    return convergence.drop(
        columns=["__source_shard", "__source_row"], errors="ignore"
    )


def overall_algorithm_summary(metrics: pd.DataFrame) -> pd.DataFrame:
    successful = metrics.loc[metrics["status"] == "success"].copy()
    preferred_metrics = [
        "hypervolume",
        "igd_plus",
        "epsilon_plus",
        "spacing",
        "objective_extent",
        "hv_fe_auc",
        "runtime_seconds",
        "feasible_rate",
        "nontrivial_feasible_rate",
        "first_fe_nontrivial_feasible_95",
        "pareto_size",
        "recommended_reputation",
        "recommended_choice_gain_pp",
        "recommended_effective_cost",
        "recommended_high_priority_coverage",
        "recommended_priority_alignment",
        "recommended_n_active_actions",
    ]
    metric_columns = [
        column for column in preferred_metrics if column in successful.columns
    ]
    rows: list[dict[str, Any]] = []
    for algorithm, group in successful.groupby("algorithm", sort=True):
        row: dict[str, Any] = {
            "algorithm": str(algorithm),
            "n_successful_runs": int(len(group)),
            "n_scenarios": int(
                group[["max_active_actions", "coverage_threshold"]]
                .drop_duplicates()
                .shape[0]
            ),
            "n_seeds": int(group["seed"].nunique()),
        }
        for column in metric_columns:
            values = (
                pd.to_numeric(group[column], errors="coerce")
                .replace([np.inf, -np.inf], np.nan)
                .dropna()
            )
            if values.empty:
                continue
            row[f"{column}_mean"] = float(values.mean())
            row[f"{column}_std"] = (
                float(values.std(ddof=1)) if len(values) > 1 else 0.0
            )
            row[f"{column}_median"] = float(values.median())
            row[f"{column}_q25"] = float(values.quantile(0.25))
            row[f"{column}_q75"] = float(values.quantile(0.75))
        rows.append(row)
    return pd.DataFrame(rows)


# =============================================================================
# 7. Main
# =============================================================================
def main() -> None:
    print(f"Base directory: {SCRIPT_DIR}")
    print(f"Metric runner: {RUNNER_FILE}")
    print(f"Output directory: {MERGED_OUTPUT_DIR}")

    for directory in SHARD_DIRS:
        if not directory.exists():
            raise FileNotFoundError(f"Shard directory not found: {directory}")

    MERGED_OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    MERGED_HV_FE_DIR.mkdir(parents=True, exist_ok=True)
    if COPY_FRONTS_TO_MERGED_DIR:
        MERGED_FRONT_DIR.mkdir(parents=True, exist_ok=True)

    runner = load_module(RUNNER_FILE, "five_algorithm_merge_runner_optimized")

    print("Stage 1/7: validating shard manifests and runner compatibility...")
    manifest_report, common_manifest = validate_manifest_compatibility(SHARD_DIRS)
    validate_runner_against_manifest(runner, common_manifest)

    print("Stage 2/7: loading and consistently deduplicating run metrics...")
    metric_frames: list[pd.DataFrame] = []
    shard_manifests: dict[str, dict[str, Any]] = {}
    for directory in SHARD_DIRS:
        manifest = read_manifest(directory).get("configuration", {})
        shard_manifests[str(directory.resolve())] = manifest
        frame = canonicalize_run_keys(read_required_csv(directory, "run_metrics.csv"))
        validate_shard_k_configuration(directory, frame, manifest)
        metric_frames.append(add_source_metadata(frame, directory))

    metrics_with_source = concatenate_nonempty(metric_frames)
    if metrics_with_source.empty:
        raise RuntimeError("No run_metrics records were loaded.")

    duplicate_mask = metrics_with_source.duplicated(RUN_KEY_COLUMNS, keep=False)
    duplicate_full_path = MERGED_OUTPUT_DIR / "duplicate_run_metrics_full.csv"
    if duplicate_mask.any():
        metrics_with_source.loc[duplicate_mask].sort_values(
            RUN_KEY_COLUMNS + ["__source_shard", "__source_row"], kind="mergesort"
        ).to_csv(duplicate_full_path, index=False, encoding="utf-8-sig")
    else:
        _remove_stale_file(duplicate_full_path)

    metrics_with_source = deduplicate_records(
        metrics_with_source,
        RUN_KEY_COLUMNS,
        "run_metrics.csv",
        MERGED_OUTPUT_DIR / "duplicate_run_metrics_audit.csv",
    )
    source_by_run = selected_source_map(metrics_with_source)

    expected_algorithms = tuple(
        str(item["name"]) for item in common_manifest["algorithms"]
    )
    expected_seeds = tuple(int(value) for value in common_manifest["seeds"])
    expected_rhos = tuple(
        float(value) for value in common_manifest["coverage_threshold_scenarios"]
    )
    completeness = validate_scenario_completeness(
        metrics_with_source,
        expected_algorithms,
        expected_seeds,
        expected_rhos,
    )

    metrics = metrics_with_source.drop(
        columns=["__source_shard", "__source_row"], errors="ignore"
    )

    print("Stage 3/7: loading Pareto fronts and recomputing final PF metrics...")
    fronts, front_sources = load_all_fronts(SHARD_DIRS)
    successful_keys = {
        run_key_from_values(
            row.max_active_actions,
            row.coverage_threshold,
            row.algorithm,
            row.seed,
        )
        for row in metrics.loc[metrics["status"] == "success"].itertuples()
    }
    validate_front_source_consistency(
        successful_keys, source_by_run, fronts, front_sources
    )

    if COPY_FRONTS_TO_MERGED_DIR:
        for key in sorted(successful_keys):
            k, rho, algorithm, seed = key
            filename = (
                f"{runner.scenario_tag(k, rho)}_{algorithm}_seed_{seed}.csv"
            )
            fronts[key].to_csv(
                MERGED_FRONT_DIR / filename, index=False, encoding="utf-8-sig"
            )

    n_options = infer_service_element_count(fronts)
    manifest_n_options = int(common_manifest["n_options"])
    if n_options != manifest_n_options:
        raise RuntimeError(
            f"Service-element count differs: fronts={n_options}, "
            f"manifest={manifest_n_options}."
        )

    population_multiplier = int(common_manifest["population_multiplier"])
    minimum_population = int(common_manifest["minimum_population_size"])
    maximum_population = int(common_manifest["maximum_population_size"])
    runner.METRIC_FRONT_CAP = int(
        np.clip(
            population_multiplier * n_options,
            minimum_population,
            maximum_population,
        )
    )

    # This overwrites any stale quality columns already present in run_metrics.
    metrics, coverage = runner.attach_quality_metrics(metrics, fronts)
    coverage_summary = runner.summarize_pairwise_coverage(coverage)

    print("Stage 4/7: rebuilding HV-FE/IGD+-FE from raw snapshot points...")
    if RECOMPUTE_HV_FE_FROM_SNAPSHOTS:
        checkpoint_metadata = load_checkpoint_metadata(SHARD_DIRS, source_by_run)
        checkpoint_completeness = validate_checkpoint_completeness(
            checkpoint_metadata,
            successful_keys,
            runner.HV_FE_CHECKPOINT_FRACTIONS,
        )
        snapshot_points = load_snapshot_points(SHARD_DIRS, source_by_run)
        validate_final_snapshot_points(
            snapshot_points,
            successful_keys,
            max(runner.HV_FE_CHECKPOINT_FRACTIONS),
        )
        snapshot_records = reconstruct_snapshot_records(
            checkpoint_metadata, snapshot_points
        )
        hv_fe_curve = runner.build_hv_fe_curve(
            metrics, fronts, snapshot_records
        )
    else:
        raise RuntimeError(
            "RECOMPUTE_HV_FE_FROM_SNAPSHOTS=False is disabled for this validated "
            "merge path because reusing per-shard metric values can preserve stale "
            "HV implementations."
        )

    hv_fe_curve, hv_monotonicity = enforce_and_check_hv_fe_monotonicity(
        hv_fe_curve
    )
    metrics = runner.attach_hv_fe_auc(metrics, hv_fe_curve)
    missing_auc = metrics.loc[
        (metrics["status"] == "success") & metrics["hv_fe_auc"].isna(),
        RUN_KEY_COLUMNS,
    ]
    if STRICT_COMPLETENESS and not missing_auc.empty:
        raise RuntimeError(
            "Successful runs without a complete HV-FE AUC were found:\n"
            + missing_auc.head(20).to_string(index=False)
        )
    hv_fe_summary = runner.summarize_hv_fe_curve(hv_fe_curve)
    runner.plot_hv_fe_curves(hv_fe_summary, MERGED_HV_FE_DIR)

    print("Stage 5/7: loading and deduplicating convergence history...")
    convergence = load_convergence_history(SHARD_DIRS, source_by_run)

    print("Stage 6/7: computing summaries and statistical tests...")
    summary = runner.summarize_by_scenario(metrics)
    pairwise = runner.pairwise_tests(metrics)
    friedman, ranks = runner.friedman_and_ranks(metrics)
    stability = runner.recommendation_stability(metrics)
    frequency = runner.recommended_es_frequency(metrics)
    overall = overall_algorithm_summary(metrics)

    configuration = pd.DataFrame(
        [
            {"parameter": "merged_output_dir", "value": str(MERGED_OUTPUT_DIR)},
            {"parameter": "metric_runner", "value": str(RUNNER_FILE)},
            {
                "parameter": "source_shards",
                "value": " | ".join(str(path) for path in SHARD_DIRS),
            },
            {
                "parameter": "n_K_levels",
                "value": int(metrics["max_active_actions"].nunique()),
            },
            {
                "parameter": "n_rho_levels",
                "value": int(metrics["coverage_threshold"].nunique()),
            },
            {
                "parameter": "n_scenarios",
                "value": int(
                    metrics[["max_active_actions", "coverage_threshold"]]
                    .drop_duplicates()
                    .shape[0]
                ),
            },
            {
                "parameter": "algorithms",
                "value": " | ".join(expected_algorithms),
            },
            {"parameter": "seeds", "value": str(expected_seeds)},
            {"parameter": "n_service_elements", "value": int(n_options)},
            {
                "parameter": "metric_front_cap",
                "value": int(runner.METRIC_FRONT_CAP),
            },
            {
                "parameter": "quality_metric_scaling",
                "value": (
                    "joint normalization and empirical reference front within "
                    "each fixed (K, rho) scenario"
                ),
            },
            {
                "parameter": "HV_FE_source",
                "value": (
                    "rebuilt from hv_fe_snapshot_points.csv.gz using checkpoint "
                    "metadata from hv_fe_curve.csv"
                ),
            },
            {
                "parameter": "HV_FE_definition",
                "value": "cumulative attained nondominated front",
            },
            {
                "parameter": "HV_FE_exact_monotonic_clamp",
                "value": bool(ENFORCE_EXACT_HV_FE_MONOTONICITY),
            },
            {"parameter": "pooled_test_blocks", "value": "(K, rho, seed)"},
        ]
    )

    print("Stage 7/7: writing merged files...")
    runner.OUTPUT_DIR = MERGED_OUTPUT_DIR
    runner.OUTPUT_EXCEL = MERGED_EXCEL
    runner.save_outputs(
        metrics,
        summary,
        pairwise,
        friedman,
        ranks,
        coverage,
        coverage_summary,
        convergence,
        hv_fe_curve,
        hv_fe_summary,
        stability,
        frequency,
        configuration,
    )

    extra_csv_outputs = {
        "overall_algorithm_summary.csv": overall,
        "scenario_completeness.csv": completeness,
        "hv_fe_checkpoint_completeness.csv": checkpoint_completeness,
        "hv_fe_monotonicity_check.csv": hv_monotonicity,
        "shard_manifest_comparison.csv": manifest_report,
    }
    for filename, frame in extra_csv_outputs.items():
        frame.to_csv(
            MERGED_OUTPUT_DIR / filename,
            index=False,
            encoding="utf-8-sig",
        )

    if not snapshot_points.empty:
        snapshot_export = snapshot_points.drop(
            columns=["__source_shard", "__source_row"], errors="ignore"
        )
        snapshot_export.to_csv(
            MERGED_OUTPUT_DIR / "hv_fe_snapshot_points.csv.gz",
            index=False,
            encoding="utf-8",
            compression="gzip",
        )

    with pd.ExcelWriter(
        MERGED_EXCEL,
        engine="openpyxl",
        mode="a",
        if_sheet_exists="replace",
    ) as writer:
        overall.to_excel(
            writer, sheet_name="Overall_algorithm_summary", index=False
        )
        completeness.to_excel(
            writer, sheet_name="Scenario_completeness", index=False
        )
        checkpoint_completeness.to_excel(
            writer, sheet_name="HV_FE_checkpoint_check", index=False
        )
        hv_monotonicity.to_excel(
            writer, sheet_name="HV_FE_monotonicity", index=False
        )
        manifest_report.to_excel(
            writer, sheet_name="Shard_manifests", index=False
        )

    expected_outputs = [
        MERGED_EXCEL,
        MERGED_OUTPUT_DIR / "run_metrics.csv",
        MERGED_OUTPUT_DIR / "hv_fe_curve.csv",
        MERGED_OUTPUT_DIR / "overall_algorithm_summary.csv",
        MERGED_OUTPUT_DIR / "scenario_completeness.csv",
        MERGED_OUTPUT_DIR / "hv_fe_checkpoint_completeness.csv",
        MERGED_OUTPUT_DIR / "hv_fe_monotonicity_check.csv",
        MERGED_OUTPUT_DIR / "shard_manifest_comparison.csv",
    ]
    missing_outputs = [path for path in expected_outputs if not path.exists()]
    if missing_outputs:
        raise RuntimeError(
            "The merge finished without creating all required output files:\n"
            + "\n".join(str(path) for path in missing_outputs)
        )

    n_success = int((metrics["status"] == "success").sum())
    n_failed = int((metrics["status"] != "success").sum())
    n_scenarios = int(
        metrics[["max_active_actions", "coverage_threshold"]]
        .drop_duplicates()
        .shape[0]
    )
    n_hv_clamped = int(
        pd.to_numeric(
            hv_monotonicity.get(
                "n_hv_values_clamped", pd.Series(dtype=float)
            ),
            errors="coerce",
        ).fillna(0).sum()
    )

    print("\nMerge completed.")
    print(f"Scenarios: {n_scenarios}")
    print(f"Successful runs: {n_success}; failed runs: {n_failed}")
    print(f"Pareto fronts: {len(fronts)}")
    print(f"HV-FE values clamped for floating-point monotonicity: {n_hv_clamped}")
    print(f"Workbook: {MERGED_EXCEL}")
    print(f"Merged directory: {MERGED_OUTPUT_DIR}")


if __name__ == "__main__":
    main()
